SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT 'bba257cc742f5e2c' HASH '6f65509dc84e5e0231eef536188bc32a12fdbbbe47ab5b7a3430aad38a24362f' ADMIN;            
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;        
CREATE CACHED TABLE PUBLIC.DISPATCH(
    DISPATCHKEY INTEGER NOT NULL,
    WHENABANDONED TIMESTAMP,
    WHENCOMPLETED TIMESTAMP,
    WHENSTARTED TIMESTAMP,
    DESTINATION_NEIGHBORKEY INTEGER NOT NULL,
    TICKETEDFILE_TICKETEDFILEKEY INTEGER NOT NULL
); 
ALTER TABLE PUBLIC.DISPATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(DISPATCHKEY);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DISPATCH; 
CREATE CACHED TABLE PUBLIC.ENTRY(
    ENTRYKEY INTEGER NOT NULL,
    IDENTITY VARCHAR(255),
    WHENLASTMODIFIED TIMESTAMP,
    COMPRESSEDPATH_PATHKEY INTEGER,
    DATAPATH_PATHKEY INTEGER,
    METAPATH_PATHKEY INTEGER,
    WRAPPEDPATH_PATHKEY INTEGER
); 
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_3F PRIMARY KEY(ENTRYKEY);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ENTRY;    
CREATE CACHED TABLE PUBLIC.HIERARCHICALPATH(
    PATHKEY INTEGER NOT NULL,
    CACHEDPATH VARCHAR(255),
    NAME VARCHAR(255),
    PARENT_PATHKEY INTEGER NOT NULL
);          
ALTER TABLE PUBLIC.HIERARCHICALPATH ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(PATHKEY);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HIERARCHICALPATH;         
CREATE CACHED TABLE PUBLIC.INBOUNDREGISTRATION(
    REMOTEID VARCHAR(255),
    REGISTRATIONKEY INTEGER NOT NULL,
    DELIVERER_NEIGHBORKEY INTEGER NOT NULL
); 
ALTER TABLE PUBLIC.INBOUNDREGISTRATION ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(REGISTRATIONKEY);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INBOUNDREGISTRATION;      
CREATE CACHED TABLE PUBLIC.LASTWATCHED(
    LASTWATCHEDKEY INTEGER NOT NULL,
    LASTDATETIME TIMESTAMP NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);            
ALTER TABLE PUBLIC.LASTWATCHED ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(LASTWATCHEDKEY); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LASTWATCHED;              
CREATE CACHED TABLE PUBLIC.LOCALREGISTRATION(
    REGISTRATIONKEY INTEGER NOT NULL,
    LOCALID VARCHAR(255)
);
ALTER TABLE PUBLIC.LOCALREGISTRATION ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(REGISTRATIONKEY);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LOCALREGISTRATION;        
CREATE CACHED TABLE PUBLIC.NEIGHBOR(
    NEIGHBORKEY INTEGER NOT NULL,
    EMAIL VARCHAR(255)
);               
ALTER TABLE PUBLIC.NEIGHBOR ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(NEIGHBORKEY);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NEIGHBOR; 
CREATE CACHED TABLE PUBLIC.POI(
    POINTOFINTERESTKEY INTEGER NOT NULL,
    LEVEL INTEGER,
    STATUS INTEGER,
    WHENOCCURRED TIMESTAMP,
    GUID_POIGUIDKEY INTEGER,
    TYPE_POITYPEKEY INTEGER
);        
ALTER TABLE PUBLIC.POI ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(POINTOFINTERESTKEY);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POI;      
CREATE CACHED TABLE PUBLIC.POIATTRIBUTE(
    POIATTRIBUTEKEY INTEGER NOT NULL,
    VALUE VARCHAR(255),
    NAME_POIATTRIBUTENAMEKEY INTEGER,
    POINTOFINTEREST_POINTOFINTERESTKEY INTEGER
); 
ALTER TABLE PUBLIC.POIATTRIBUTE ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(POIATTRIBUTEKEY);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POIATTRIBUTE;             
CREATE CACHED TABLE PUBLIC.POIATTRIBUTENAME(
    POIATTRIBUTENAMEKEY INTEGER NOT NULL,
    VALUE VARCHAR(255)
);               
ALTER TABLE PUBLIC.POIATTRIBUTENAME ADD CONSTRAINT PUBLIC.CONSTRAINT_3F4 PRIMARY KEY(POIATTRIBUTENAMEKEY);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POIATTRIBUTENAME;         
CREATE CACHED TABLE PUBLIC.POIGUID(
    POIGUIDKEY INTEGER NOT NULL,
    VALUE VARCHAR(255)
); 
ALTER TABLE PUBLIC.POIGUID ADD CONSTRAINT PUBLIC.CONSTRAINT_12 PRIMARY KEY(POIGUIDKEY);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POIGUID;  
CREATE CACHED TABLE PUBLIC.POITYPE(
    POITYPEKEY INTEGER NOT NULL,
    VALUE VARCHAR(255)
); 
ALTER TABLE PUBLIC.POITYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_12E PRIMARY KEY(POITYPEKEY);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POITYPE;  
CREATE CACHED TABLE PUBLIC.SEENITEM(
    SEENITEMKEY INTEGER NOT NULL,
    ITEM VARCHAR(256) NOT NULL,
    LASTWATCHED_LASTWATCHEDKEY INTEGER NOT NULL
);      
ALTER TABLE PUBLIC.SEENITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_6A PRIMARY KEY(SEENITEMKEY);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SEENITEM; 
CREATE CACHED TABLE PUBLIC.SLICEDEXECUTION(
    SLICEDEXECUTIONKEY INTEGER NOT NULL,
    BYTES BIGINT NOT NULL,
    COUNT INTEGER NOT NULL,
    INTERVAL_INTERVALKEY INTEGER NOT NULL,
    TOPIC_TOPICKEY INTEGER NOT NULL
);  
ALTER TABLE PUBLIC.SLICEDEXECUTION ADD CONSTRAINT PUBLIC.CONSTRAINT_A1 PRIMARY KEY(SLICEDEXECUTIONKEY);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SLICEDEXECUTION;          
CREATE CACHED TABLE PUBLIC.SLICEDINTERVAL(
    INTERVALKEY INTEGER NOT NULL,
    DURATION BIGINT NOT NULL,
    WHENENDED TIMESTAMP NOT NULL
); 
ALTER TABLE PUBLIC.SLICEDINTERVAL ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(INTERVALKEY); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SLICEDINTERVAL;           
CREATE CACHED TABLE PUBLIC.SLICEDTOPIC(
    TOPICKEY INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    INTERVAL BIGINT NOT NULL
);           
ALTER TABLE PUBLIC.SLICEDTOPIC ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(TOPICKEY);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SLICEDTOPIC;              
CREATE CACHED TABLE PUBLIC.TICKETEDFILE(
    TICKETEDFILEKEY INTEGER NOT NULL,
    ARCHIVESUFFIX VARCHAR(255),
    BINARYSIZE BIGINT,
    BUNDLE VARCHAR(255) NOT NULL,
    CHECKSUM BIGINT,
    COMPRESSEDSIZE BIGINT,
    METADATASIZE BIGINT,
    PACKAGEDSIZE BIGINT,
    PLACEDSIZE BIGINT,
    PLACEMENTID VARCHAR(255),
    REMOTENUMBER INTEGER,
    REMOTEREGISTRATIONID VARCHAR(255),
    UUID VARCHAR(255),
    WHENABANDONED TIMESTAMP,
    WHENARCHIVED TIMESTAMP,
    WHENBINARYSET TIMESTAMP,
    WHENCOMPLETED TIMESTAMP,
    WHENCOMPRESSEDSET TIMESTAMP,
    WHENFLUSHED TIMESTAMP,
    WHENMETADATASET TIMESTAMP,
    WHENPACKAGEDSET TIMESTAMP,
    WHENPLACED TIMESTAMP,
    WHENRESTORED TIMESTAMP,
    WHENTICKETED TIMESTAMP,
    WHENVERIFICATIONCOMPLETED TIMESTAMP,
    WHENVERIFICATIONSTARTED TIMESTAMP,
    WHENWRAPPEDSET TIMESTAMP,
    WRAPPEDSIZE BIGINT,
    LOCALREGISTRATION_REGISTRATIONKEY INTEGER NOT NULL
);          
ALTER TABLE PUBLIC.TICKETEDFILE ADD CONSTRAINT PUBLIC.CONSTRAINT_2F PRIMARY KEY(TICKETEDFILEKEY);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TICKETEDFILE;             
CREATE CACHED TABLE PUBLIC.VERIFIED(
    VERIFIEDKEY INTEGER NOT NULL,
    WHENABANDONED TIMESTAMP,
    WHENVERIFIED TIMESTAMP,
    DESTINATION_NEIGHBORKEY INTEGER NOT NULL,
    TICKETEDFILE_TICKETEDFILEKEY INTEGER NOT NULL
);             
ALTER TABLE PUBLIC.VERIFIED ADD CONSTRAINT PUBLIC.CONSTRAINT_B7 PRIMARY KEY(VERIFIEDKEY);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VERIFIED; 
ALTER TABLE PUBLIC.VERIFIED ADD CONSTRAINT PUBLIC.FK_S4V206J3B4197VFTUJC3Y3EFV FOREIGN KEY(DESTINATION_NEIGHBORKEY) REFERENCES PUBLIC.NEIGHBOR(NEIGHBORKEY) NOCHECK;           
ALTER TABLE PUBLIC.POIATTRIBUTE ADD CONSTRAINT PUBLIC.FK_DQCG5D4KDD57JXW3G7PGAD48 FOREIGN KEY(NAME_POIATTRIBUTENAMEKEY) REFERENCES PUBLIC.POIATTRIBUTENAME(POIATTRIBUTENAMEKEY) NOCHECK;       
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.FK_7KEE6AE2UMHW4JRO0YLW322WC FOREIGN KEY(WRAPPEDPATH_PATHKEY) REFERENCES PUBLIC.HIERARCHICALPATH(PATHKEY) NOCHECK;              
ALTER TABLE PUBLIC.VERIFIED ADD CONSTRAINT PUBLIC.FK_ML0KBRDTD4J9HL3CA2CTB771R FOREIGN KEY(TICKETEDFILE_TICKETEDFILEKEY) REFERENCES PUBLIC.TICKETEDFILE(TICKETEDFILEKEY) NOCHECK;              
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.FK_196QQ757DCC1R2IEYSTSN0URC FOREIGN KEY(COMPRESSEDPATH_PATHKEY) REFERENCES PUBLIC.HIERARCHICALPATH(PATHKEY) NOCHECK;           
ALTER TABLE PUBLIC.SLICEDEXECUTION ADD CONSTRAINT PUBLIC.FK_IOCDYB7J1JQEF263126PPUB3 FOREIGN KEY(INTERVAL_INTERVALKEY) REFERENCES PUBLIC.SLICEDINTERVAL(INTERVALKEY) NOCHECK;  
ALTER TABLE PUBLIC.INBOUNDREGISTRATION ADD CONSTRAINT PUBLIC.FK_MWWMCQB98UGJ7MBNGHS785JBH FOREIGN KEY(REGISTRATIONKEY) REFERENCES PUBLIC.LOCALREGISTRATION(REGISTRATIONKEY) NOCHECK;           
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.FK_KLHH17DFLGPGSE45C7JJA6F0P FOREIGN KEY(DATAPATH_PATHKEY) REFERENCES PUBLIC.HIERARCHICALPATH(PATHKEY) NOCHECK; 
ALTER TABLE PUBLIC.SLICEDEXECUTION ADD CONSTRAINT PUBLIC.FK_C9QICWB6HFCQ4PVKUL56QD0BT FOREIGN KEY(TOPIC_TOPICKEY) REFERENCES PUBLIC.SLICEDTOPIC(TOPICKEY) NOCHECK;             
ALTER TABLE PUBLIC.DISPATCH ADD CONSTRAINT PUBLIC.FK_68L6TCA3CUFHRCQ8WJDH9KXYG FOREIGN KEY(DESTINATION_NEIGHBORKEY) REFERENCES PUBLIC.NEIGHBOR(NEIGHBORKEY) NOCHECK;           
ALTER TABLE PUBLIC.HIERARCHICALPATH ADD CONSTRAINT PUBLIC.FK_LP7HP17D5USWPG7F2LMX41GF5 FOREIGN KEY(PARENT_PATHKEY) REFERENCES PUBLIC.HIERARCHICALPATH(PATHKEY) NOCHECK;        
ALTER TABLE PUBLIC.DISPATCH ADD CONSTRAINT PUBLIC.FK_IU0C7BRNG4M5U1NIYF2VW2LXR FOREIGN KEY(TICKETEDFILE_TICKETEDFILEKEY) REFERENCES PUBLIC.TICKETEDFILE(TICKETEDFILEKEY) NOCHECK;              
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.FK_IXQWVL82YA21JHS3OOLNJ5A4B FOREIGN KEY(METAPATH_PATHKEY) REFERENCES PUBLIC.HIERARCHICALPATH(PATHKEY) NOCHECK; 
ALTER TABLE PUBLIC.INBOUNDREGISTRATION ADD CONSTRAINT PUBLIC.FK_Q0XQ8HR9HADCXSA299M4M1OR0 FOREIGN KEY(DELIVERER_NEIGHBORKEY) REFERENCES PUBLIC.NEIGHBOR(NEIGHBORKEY) NOCHECK;  
ALTER TABLE PUBLIC.POI ADD CONSTRAINT PUBLIC.FK_56EXSCEGUYNW0A0XMNCC86IFT FOREIGN KEY(TYPE_POITYPEKEY) REFERENCES PUBLIC.POITYPE(POITYPEKEY) NOCHECK;          
ALTER TABLE PUBLIC.SEENITEM ADD CONSTRAINT PUBLIC.FK_PUER2G1L0R9RDKJB3LKBYM9JB FOREIGN KEY(LASTWATCHED_LASTWATCHEDKEY) REFERENCES PUBLIC.LASTWATCHED(LASTWATCHEDKEY) NOCHECK;  
ALTER TABLE PUBLIC.POIATTRIBUTE ADD CONSTRAINT PUBLIC.FK_53UK8HO1K2OUBJ0IUM64SSSJ4 FOREIGN KEY(POINTOFINTEREST_POINTOFINTERESTKEY) REFERENCES PUBLIC.POI(POINTOFINTERESTKEY) NOCHECK;          
ALTER TABLE PUBLIC.POI ADD CONSTRAINT PUBLIC.FK_RKICV27SIHJ2G7W4XQLJTVNYP FOREIGN KEY(GUID_POIGUIDKEY) REFERENCES PUBLIC.POIGUID(POIGUIDKEY) NOCHECK;          
ALTER TABLE PUBLIC.TICKETEDFILE ADD CONSTRAINT PUBLIC.FK_Q2YB4KYMJO9XNBLAC8HHTYJE FOREIGN KEY(LOCALREGISTRATION_REGISTRATIONKEY) REFERENCES PUBLIC.LOCALREGISTRATION(REGISTRATIONKEY) NOCHECK; 
